// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Sjja6VOLgjhPU9otxmsCr_hpZcfouc8',
    appId: '1:250989835769:web:79ac6e9013edbcf9e6b928',
    messagingSenderId: '250989835769',
    projectId: 'to-do-list-49926',
    authDomain: 'to-do-list-49926.firebaseapp.com',
    storageBucket: 'to-do-list-49926.appspot.com',
    measurementId: 'G-JSHBX6N5FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIQ-GPze9-inkQosE5_Dh11HnY9BaWbjY',
    appId: '1:250989835769:android:8a196197b72c4304e6b928',
    messagingSenderId: '250989835769',
    projectId: 'to-do-list-49926',
    storageBucket: 'to-do-list-49926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsy8ImUgU412U1IMS5l6ZIwxjjfbqSfEw',
    appId: '1:250989835769:ios:7badc618b7a3bce7e6b928',
    messagingSenderId: '250989835769',
    projectId: 'to-do-list-49926',
    storageBucket: 'to-do-list-49926.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsy8ImUgU412U1IMS5l6ZIwxjjfbqSfEw',
    appId: '1:250989835769:ios:7eb829fd326c2430e6b928',
    messagingSenderId: '250989835769',
    projectId: 'to-do-list-49926',
    storageBucket: 'to-do-list-49926.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
